import Head from 'next/head'
import useSWR from 'swr'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  BookTitle,
  BookContainer,
  AuthorTitle

} from '../components/sharedstyles'
import { useRouter } from 'next/router'
import Cards from '../components/cards'
import Book from '../components/Book';
//Shows all the books in the database
export default function handler() {
    const router = useRouter()
    const {title} = router.query;
    const fetcher = (url) => fetch(url).then((res) => res.json());

    const { data, error } = useSWR('/api/books/'+title, fetcher);
    if (error) return <div>failed to load</div>
    if (!data) return <div>loading...</div>
    
    //Format Data "author": "Emily Bront\u00eb",
    //   "country": "United Kingdom",
    //   "imageLink": "images/wuthering-heights.jpg",
    //   "language": "English",
    //   "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    //   "pages": 342,
    //   "title": "Wuthering Heights",
    //   "year": 1847
    const books = data.map((book, index) => (
        <Book key={index} book={book} />
    ));

    return (
        <Container>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main>
            <Title>
            {title}
            </Title>
            
            {books}

            <Cards name="Back" link="/" />
        </Main>
        </Container>
    )
}