import Head from 'next/head'
import useSWR from 'swr'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  BookTitle,
  BookContainer,
  AuthorTitle

} from '../components/sharedstyles'
import Cards from '../components/cards'
import Book from '../components/Book';
//Shows all the books in the database
const fetcher = (url) => fetch(url).then((res) => res.json());
export default function Home() {

  const { data, error } = useSWR('/api/authors', fetcher);
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  
  //Style the json data to be displayed in a table
  const authors = data.map((author, index) => (
    <AuthorTitle key={index}>
      {author}
    </AuthorTitle>
  ));
  return (
    <Container>
      <Head>
        <title>Authors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Cards name="Home" link="/" />

        <Title>
          Authors
        </Title>
        
        <BookContainer>
          {authors}
        </BookContainer>
        {/* <Cards /> */}
      </Main>
    </Container>
  )
}