import Head from 'next/head'
import useSWR from 'swr'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  BookTitle,
  BookContainer

} from '../components/sharedstyles'
import Cards from '../components/cards'
import Book from '../components/Book';
//Shows all the books in the database
const fetcher = (url) => fetch(url).then((res) => res.json());
export default function Home() {

  const { data, error } = useSWR('/api/books', fetcher);
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  
  //Style the json data to be displayed in a table
  const books = data.map((book, index) => (
    <Cards name={book.title}link = {book.title} />
  ));
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Books
        </Title>
        
        <BookContainer>
          {books}
        </BookContainer>
        {/* <Cards /> */}
      </Main>
    </Container>
  )
}